active-theme=DukuSlice
left-stick-mod=D-pad
right-stick-mod=Disabled
mph-manual-speed=100
mph-auto-release-delay-ms=400
sm64-auto-center-hold-frames=12
sm64-auto-release-delay-ms=1000
cursor-speed-limit=300
sm64-dpad-deadzone-percent=75
left-stick-scale-left-percent=100
left-stick-scale-right-percent=100
left-stick-scale-up-percent=100
left-stick-scale-down-percent=100
# Fallback parameters
text-font=assets/themes/DukuSlice/comfortaa-latin-400-normal.ttf
background-dark=#cc3333
background-light=#ff5050
text-color=#330c00
hint-color=#ff7272
button-fill=#ff7272
button-outline=#62d55d
button-outline-width=6
